import Img1 from "../../assets/services/img1.jpg"
import Img2 from "../../assets/services/img2.jpg"
import Img3 from "../../assets/services/img3.jpg"
import Img4 from "../../assets/services/img4.jpg"
import Img5 from "../../assets/services/img5.jpg"
import Img6 from "../../assets/services/img6.jpg"
import Img7 from "../../assets/services/img7.jpg"
import Img8 from "../../assets/services/img8.jpg"
import Img9 from "../../assets/services/img9.jpg"
import Img10 from "../../assets/services/img10.jpg"
import Img11 from "../../assets/services/img11.jpg"
import Img12 from "../../assets/services/img12.jpg"
import Img13 from "../../assets/services/img13.jpg"
import Img14 from "../../assets/services/img14.jpg"
import Img15 from "../../assets/services/img15.jpg"
import Img16 from "../../assets/services/img16.jpg"
import Img17 from "../../assets/services/img17.jpg"
import Img18 from "../../assets/services/img18.jpg"

export const ImagesServ = [
  { img: Img1 },
  { img: Img2 },
  { img: Img3 },
  { img: Img4 },
  { img: Img5 },
  { img: Img6 },
  { img: Img7 },
  { img: Img8 },
  { img: Img9 },
  { img: Img10 },
  { img: Img11 },
  { img: Img12 },
  { img: Img13 },
  { img: Img14 },
  { img: Img15 },
  { img: Img16 },
  { img: Img17 },
  { img: Img18 },
]